apiVersion: v1
kind: Service
metadata:
  name: runner-vnightly-53
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80": "runner-vnightly-53-backendconfig"}}'
spec:
  selector:
    app.kubernetes.io/name: runner-vnightly-53
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: runner-vnightly-53-backendconfig
spec:
  timeoutSec: 660
  connectionDraining:
    drainingTimeoutSec: 720
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: runner-vnightly-53
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: runner-vnightly-53
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 400m
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-vnightly-53
  labels:
    app.kubernetes.io/name: runner-vnightly-53
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: runner-vnightly-53
  minReadySeconds: 60
  progressDeadlineSeconds: 7200
  template:
    metadata:
      labels:
        app.kubernetes.io/name: runner-vnightly-53
      annotations:
        commit_sha: "7080d8b9f0b1ed16a63bb741e4942ce4f3ad6559"
        timestamp: "1629169987922"
    spec:
      containers:
        - image: us.gcr.io/swift-playground-fbe87/runner:nightly-5.3
          name: runner-vnightly-53
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /runner/nightly-5.3/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 60
            periodSeconds: 300
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /runner/nightly-5.3/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 60
            periodSeconds: 300
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 20
            periodSeconds: 60
            failureThreshold: 2
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: sandbox
              mountPath: /tmp
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: sandbox
          hostPath:
            path: /tmp
      terminationGracePeriodSeconds: 60
---

