apiVersion: v1
kind: Service
metadata:
  name: %NAME%
spec:
  selector:
    app.kubernetes.io/name: %NAME%
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: %NAME%
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: %NAME%
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 100m
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %NAME%
  labels:
    app.kubernetes.io/name: %NAME%
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: %NAME%
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 60
  progressDeadlineSeconds: 1800
  template:
    metadata:
      labels:
        app.kubernetes.io/name: %NAME%
      annotations:
        commit_sha: "%COMMIT_SHA%"
    spec:
      nodeSelector:
        name: defaultpool
      containers:
        - image: %IMAGE%
          name: %NAME%
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /runner/%VERSION%/health
              port: 8080
            initialDelaySeconds: 300
            timeoutSeconds: 60
            periodSeconds: 300
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /runner/%VERSION%/health
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 60
            periodSeconds: 300
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 20
            periodSeconds: 60
            failureThreshold: 2
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 32Mi
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: sandbox
              mountPath: /tmp
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: sandbox
          hostPath:
            path: /tmp
      terminationGracePeriodSeconds: 60
---

