apiVersion: v1
kind: Service
metadata:
  name: %NAME%
spec:
  selector:
    app.kubernetes.io/name: %NAME%
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: %NAME%
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: %NAME%
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: 100m
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %NAME%
  labels:
    app.kubernetes.io/name: %NAME%
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: %NAME%
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 20
  progressDeadlineSeconds: 3600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: %NAME%
      annotations:
        commit_sha: "%COMMIT_SHA%"
        timestamp: "%TIMESTAMP%"
    spec:
      nodeSelector:
        name: defaultpool
      initContainers:
        - image: %IMAGE%-init
          name: %NAME%-init
          imagePullPolicy: Always
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      containers:
        - image: %IMAGE%
          name: %NAME%
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /runner/%VERSION%/health
              port: 8080
            initialDelaySeconds: 180
            timeoutSeconds: 20
            periodSeconds: 30
            failureThreshold: 1
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 128Mi
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: sandbox
              mountPath: /tmp
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: sandbox
          hostPath:
            path: /tmp
      terminationGracePeriodSeconds: 30
---

