name: Build and Push Docker Images
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push Docker Images
        run: |
          set -e

          versions=($(cat versions.txt | tr "\n" " "))
          for version in "${versions[@]}"; do
            docker build --build-arg version="$version" --rm --tag "swiftfiddle/runner:$version" .
            docker push "swiftfiddle/runner:$version"
          done
