name: Deploy Swift nightly snapshot runners
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GKE_CLUSTER: swiftfiddle-cluster
  GKE_ZONE: us-central1-c

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ env.GCP_SA_KEY }}

      - name: Deploy
        run: |
          set -ex

          cat <<-EOF > versions.txt
          nightly-main
          nightly-5.5
          nightly-5.4
          nightly-5.3
          EOF

          /bin/bash k8s/pod.yaml.sh
          kubectl apply -f k8s/pod.yaml

          versions=($(cat versions.txt | tr "\n" " "))
          for version in "${versions[@]}"; do
            name="runner-v$(sed 's/\.//g' <<<"$version")"
            kubectl rollout status deployment/$name
          done

          kubectl get services -o wide
